name: release

on:
  workflow_dispatch:
    inputs:
      first-version:
        description: "是否发布首个版本"
        required: true
        type: choice
        options:
          - "false"
          - "true"

jobs:
  release:
    if: github.ref_name == 'v1.x'
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-pnpm

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Unit test
        run: npm run test

      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version
        run: npm run ci:version -- --first-version=${{github.event.inputs.first-version}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        run: npx lerna publish from-git --yes --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: FrontEndDev-org/npm-mirror-sync-action@v1
